name: love_day_counter
description: "Ung dung dem ngay yeu - dung ca nhan"
publish_to: 'none'
version: 1.2.1+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  intl: ^0.20.3
  google_sign_in: ^6.2.1

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^19.5.0

  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  home_widget: ^0.9.3
  uuid: ^4.5.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_app.png"
  min_sdk_android: 21
