name: love_day_counter
description: "Ung dung dem ngay yeu - dung ca nhan"
publish_to: 'none'
version: 1.2.2+6

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  intl: ^0.20.3
  google_sign_in: ^7.2.0

  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0
  firebase_messaging: ^16.6.0
  flutter_local_notifications: ^22.3.0

  flutter_secure_storage: ^11.0.0
  local_auth: ^3.0.2
  home_widget: ^0.9.4
  uuid: ^4.5.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_app.png"
  min_sdk_android: 21
